name: CI

on:
  push:
    branches: [master]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "test.txt"
    - name: File exists
    if: steps.check_files.outputs.files_exist == 'true' 
    run: echo "File exists!"
